#!/bin/bash
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -6 4
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -1 5
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -10 3
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
sbatch scripts/slurm_run.sh -14 0.5
