#!/bin/bash
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
sbatch scripts/slurm_run.sh -12 1
